#!/bin/bash
#
# Cordless Production Setup Script
# Clones the repo (if needed) and generates a configured .env file
#

set -e

REPO_URL="https://github.com/kaitwalla/cordless.git"
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

echo ""
echo "=========================================="
echo "  Cordless Production Setup"
echo "=========================================="
echo ""

# Check for required commands
for cmd in git openssl docker; do
    if ! command -v $cmd &> /dev/null; then
        echo -e "${RED}Error: $cmd is required but not installed.${NC}"
        exit 1
    fi
done

# Get domain from argument or environment variable
DOMAIN="${1:-$DOMAIN}"

if [ -z "$DOMAIN" ]; then
    echo -e "${RED}Error: Domain is required.${NC}"
    echo ""
    echo "Usage:"
    echo "  bash <(curl -fsSL https://raw.githubusercontent.com/kaitwalla/cordless/main/setup-production.sh) chat.example.com"
    echo ""
    echo "Or set DOMAIN environment variable:"
    echo "  DOMAIN=chat.example.com bash <(curl -fsSL https://raw.githubusercontent.com/kaitwalla/cordless/main/setup-production.sh)"
    exit 1
fi

echo -e "Setting up Cordless for: ${GREEN}$DOMAIN${NC}"
echo ""

# Check if we're already in a Cordless repo
if [ -f "docker-compose.production.yml" ] && [ -f "Gemfile" ] && [ -d ".git" ]; then
    echo -e "${GREEN}Detected existing Cordless repository.${NC}"
    INSTALL_DIR="."
else
    # Clone the repository
    INSTALL_DIR="${INSTALL_DIR:-cordless}"

    if [ -d "$INSTALL_DIR" ]; then
        echo -e "${YELLOW}Directory '$INSTALL_DIR' already exists.${NC}"
        echo -n "Remove it and continue? [y/N] "
        read -r REPLY < /dev/tty
        if [[ ! $REPLY =~ ^[Yy]$ ]]; then
            echo "Aborted."
            exit 1
        fi
        rm -rf "$INSTALL_DIR"
    fi

    echo "Cloning Cordless repository..."
    git clone --depth 1 "$REPO_URL" "$INSTALL_DIR"
    cd "$INSTALL_DIR"
fi

echo ""
echo "Generating secrets..."

# Generate secrets
SECRET_KEY_BASE=$(openssl rand -hex 64)
REDIS_PASSWORD=$(openssl rand -hex 32)
LIVEKIT_API_KEY=$(openssl rand -hex 16)
LIVEKIT_API_SECRET=$(openssl rand -hex 32)

echo "  - SECRET_KEY_BASE"
echo "  - REDIS_PASSWORD"
echo "  - LIVEKIT_API_KEY"
echo "  - LIVEKIT_API_SECRET"

# Check for existing .env
if [ -f ".env" ]; then
    echo ""
    echo -e "${YELLOW}.env file already exists.${NC}"
    echo -n "Overwrite it? [y/N] "
    read -r REPLY < /dev/tty
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "Keeping existing .env file."
        echo ""
        echo "Building Docker images..."
        docker compose -f docker-compose.production.yml build
        echo ""
        echo -e "${GREEN}Build complete!${NC}"
        echo "Run: docker compose -f docker-compose.production.yml up -d"
        exit 0
    fi
fi

# Create .env file
echo ""
echo "Creating .env file..."

cat > .env << EOF
# Cordless Production Configuration
# Generated by setup-production.sh on $(date)

# ===================
# Required Settings
# ===================

# Your domain name (used by Caddy for SSL certificates)
DOMAIN=$DOMAIN

# Rails secret key (auto-generated)
SECRET_KEY_BASE=$SECRET_KEY_BASE

# Redis password (auto-generated)
REDIS_PASSWORD=$REDIS_PASSWORD

# LiveKit configuration (auto-generated)
LIVEKIT_API_KEY=$LIVEKIT_API_KEY
LIVEKIT_API_SECRET=$LIVEKIT_API_SECRET
LIVEKIT_URL=wss://$DOMAIN/livekit

# ===================
# Optional Settings
# ===================

# Web Push Notifications
# Generate with: docker compose -f docker-compose.production.yml run --rm web bundle exec rake vapid:generate
VAPID_PUBLIC_KEY=
VAPID_PRIVATE_KEY=

# Storage Configuration
# Options: "local" (default) or "amazon" for S3
STORAGE_SERVICE=local

# AWS S3 Configuration (required when STORAGE_SERVICE=amazon)
# AWS_ACCESS_KEY_ID=
# AWS_SECRET_ACCESS_KEY=
# AWS_REGION=us-east-1
# AWS_S3_BUCKET=

# Persistent Storage Paths (defaults to ./data subdirectories)
# STORAGE_PATH=./data/storage
# REDIS_DATA_PATH=./data/redis
# CADDY_DATA_PATH=./data/caddy/data
# CADDY_CONFIG_PATH=./data/caddy/config

# Error Tracking
# SENTRY_DSN=
EOF

echo ""
echo "Building Docker images (this may take a few minutes)..."
docker compose -f docker-compose.production.yml build

echo ""
echo -e "${GREEN}=========================================="
echo "  Setup Complete!"
echo "==========================================${NC}"
echo ""
echo "Cordless has been installed to: $(pwd)"
echo ""
echo "Next steps:"
echo ""
echo "  1. Make sure ports 80, 443, 7881 (TCP), and 7882 (UDP) are open"
echo ""
echo "  2. Start the application:"
echo "     docker compose -f docker-compose.production.yml up -d"
echo ""
echo "  3. View logs:"
echo "     docker compose -f docker-compose.production.yml logs -f"
echo ""
echo "  4. Visit https://$DOMAIN to complete setup"
echo ""
echo -e "${YELLOW}Note: SSL certificates will be automatically provisioned by Caddy"
echo -e "on first request. This may take a moment.${NC}"
echo ""
