#!/bin/bash
#
# Cordless Production Setup Script
# Downloads required files and generates a configured .env file
#

set -e

REPO_RAW_URL="https://raw.githubusercontent.com/kaitwalla/cordless/main"
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

echo ""
echo "=========================================="
echo "  Cordless Production Setup"
echo "=========================================="
echo ""

# Check for required commands
for cmd in curl openssl; do
    if ! command -v $cmd &> /dev/null; then
        echo -e "${RED}Error: $cmd is required but not installed.${NC}"
        exit 1
    fi
done

# Check for Docker
if ! command -v docker &> /dev/null; then
    echo -e "${YELLOW}Warning: Docker is not installed. You'll need it to run Cordless.${NC}"
fi

# Get domain from argument, environment variable, or prompt
DOMAIN="${1:-$DOMAIN}"

if [ -z "$DOMAIN" ]; then
    echo -e "${RED}Error: Domain is required.${NC}"
    echo ""
    echo "Usage:"
    echo "  bash <(curl -fsSL https://raw.githubusercontent.com/kaitwalla/cordless/main/setup-production.sh) chat.example.com"
    echo ""
    echo "Or set DOMAIN environment variable:"
    echo "  DOMAIN=chat.example.com bash <(curl -fsSL https://raw.githubusercontent.com/kaitwalla/cordless/main/setup-production.sh)"
    exit 1
fi

echo -e "Setting up Cordless for: ${GREEN}$DOMAIN${NC}"

echo ""
echo "Downloading production files..."

# Download required files
curl -fsSL "$REPO_RAW_URL/docker-compose.production.yml" -o docker-compose.production.yml
echo "  - docker-compose.production.yml"

curl -fsSL "$REPO_RAW_URL/Caddyfile" -o Caddyfile
echo "  - Caddyfile"

curl -fsSL "$REPO_RAW_URL/livekit.yaml" -o livekit.yaml
echo "  - livekit.yaml"

curl -fsSL "$REPO_RAW_URL/Dockerfile" -o Dockerfile
echo "  - Dockerfile"

echo ""
echo "Generating secrets..."

# Generate secrets
SECRET_KEY_BASE=$(openssl rand -hex 64)
REDIS_PASSWORD=$(openssl rand -hex 32)
LIVEKIT_API_KEY=$(openssl rand -hex 16)
LIVEKIT_API_SECRET=$(openssl rand -hex 32)

echo "  - SECRET_KEY_BASE"
echo "  - REDIS_PASSWORD"
echo "  - LIVEKIT_API_KEY"
echo "  - LIVEKIT_API_SECRET"

# Create .env file
echo ""
echo "Creating .env file..."

cat > .env << EOF
# Cordless Production Configuration
# Generated by setup-production.sh on $(date)

# ===================
# Required Settings
# ===================

# Your domain name (used by Caddy for SSL certificates)
DOMAIN=$DOMAIN

# Rails secret key (auto-generated)
SECRET_KEY_BASE=$SECRET_KEY_BASE

# Redis password (auto-generated)
REDIS_PASSWORD=$REDIS_PASSWORD

# LiveKit configuration (auto-generated)
LIVEKIT_API_KEY=$LIVEKIT_API_KEY
LIVEKIT_API_SECRET=$LIVEKIT_API_SECRET
LIVEKIT_URL=wss://$DOMAIN/livekit

# ===================
# Optional Settings
# ===================

# Web Push Notifications
# Generate with: docker compose -f docker-compose.production.yml run --rm web bundle exec rake vapid:generate
VAPID_PUBLIC_KEY=
VAPID_PRIVATE_KEY=

# Storage Configuration
# Options: "local" (default) or "amazon" for S3
STORAGE_SERVICE=local

# AWS S3 Configuration (required when STORAGE_SERVICE=amazon)
# AWS_ACCESS_KEY_ID=
# AWS_SECRET_ACCESS_KEY=
# AWS_REGION=us-east-1
# AWS_S3_BUCKET=

# Persistent Storage Paths (defaults to ./data subdirectories)
# STORAGE_PATH=./data/storage
# REDIS_DATA_PATH=./data/redis
# CADDY_DATA_PATH=./data/caddy/data
# CADDY_CONFIG_PATH=./data/caddy/config

# Error Tracking
# SENTRY_DSN=
EOF

echo ""
echo -e "${GREEN}=========================================="
echo "  Setup Complete!"
echo "==========================================${NC}"
echo ""
echo "Files created:"
echo "  - docker-compose.production.yml"
echo "  - Caddyfile"
echo "  - livekit.yaml"
echo "  - Dockerfile"
echo "  - .env"
echo ""
echo "Next steps:"
echo ""
echo "  1. Review and edit .env if needed"
echo ""
echo "  2. Make sure ports 80, 443, 7881 (TCP), and 7882 (UDP) are open"
echo ""
echo "  3. Build and start the application:"
echo "     docker compose -f docker-compose.production.yml build"
echo "     docker compose -f docker-compose.production.yml up -d"
echo ""
echo "  4. View logs:"
echo "     docker compose -f docker-compose.production.yml logs -f"
echo ""
echo "  5. Visit https://$DOMAIN to complete setup"
echo ""
echo -e "${YELLOW}Note: SSL certificates will be automatically provisioned by Caddy"
echo -e "on first request. This may take a moment.${NC}"
echo ""
